collections:
  go:
    output: false
  lapcomp:
    output: true
    permalink: /:collection/:name/
gems:
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from
plugins:
  - jekyll-redirect-from
